### ISSUE TITLE
sendDirectMessage() doesn't work

### ISSUE THREAD

**Issue by hmnd** [ctrezevant/PyEdsby#6]
Whenever I try to use the sendDirectMessage function, it returns `{"errorstr":"No target node specified","when":"2017-05-04 17:17:38","error":1040}`. Not sure what target node is referring to.

**Comment by hmnd** [comment]
Figured it out. there's no need for a 'to' key to be passed in the payload. Instead, the function should look like this:
```
    def sendDirectMessage(self, message):
        payload = {
            '_formkey': self.studentData['formkey'],
            'nodetype': message['nodetype'],
            'body': message['text'],
            'media-fill-include-integrations-integrationfiledata': message['filedata'],
            'media-fill-include-integrations-integrationfiles': message['files']
        }
        return requests.post(
            'https://' + self.edsbyHost +
            '/core/create/' + message['to'] + '?xds=MessagesCompose&permaLinkKey=false&_processed=true',
            data=payload, cookies=self.getCookies(), headers=self.getHeaders()).json()
```

**Comment by chtzvt** [comment]
Ah, I see. I had initially tried to get the function to craft payloads like the web app does, but clearly I hadn't got it right. Nice detective work!!
